POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Paving the way to quantum supercomputers",
    "author": "University of Oxford",
    "url": "https://www.sciencedaily.com/releases/2025/02/250205130938.htm",
    "likes": 0
}